version: '3.9'

services:
  traefik:
    image: traefik:v2.6
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--log.level=DEBUG"
      - "--accesslog"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ipwhitelist.yml:/config/ipwhitelist.yml

  ethexporter:
    image: hunterlong/ethexporter:latest
    container_name: ethexporter
    environment:
      - GETH=https://sepolia.infura.io/v3/INFURA-KEY
      - PORT=9308
    ports:
      - "9308:9308"
    volumes:
      - ./addresses.txt:/app/addresses.txt
      - ethexporter_data:/app/data

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana`)"  # Adjust Host rule
      - "traefik.http.routers.grafana.entrypoints=web"
      - "traefik.http.routers.grafana.middlewares=test-ipwhitelist"
      - "traefik.http.middlewares.test-ipwhitelist.ipwhitelist.sourcerange=127.0.0.1/32,192.168.1.14"  # IP whitelist
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=test123*
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  ethexporter_data:
  prometheus_data:
  grafana_data:
